### ISSUE TITLE
Export to Excel format generates file with some encoding problems

### ISSUE THREAD

**Issue by marblestation** [adsabs/author_affiliation_service#15] opened 2018-02-23 21:25 UTC
To reproduce:

1. Go to qa
2. Search author:"^accomazzi, A."
3. Click export - author affiliation
4. Select excel format from the dropdown list
5. Press export
6. Open the downloaded file with LibreOffice, Numbers or Microsoft Excel

**Comment by golnazads** [comment] 2018-02-24 20:32
Created a test client html and verified that service returns properly
formatted excel spreadsheet that is saved and open with no issue.

**Comment by aaccomazzi** [comment] 2018-02-25 20:00
I'm also finding issues with excel export from BBB and was able to replicate via the crresponding API calls, see example below (set ADS_DEV_KEY to valid token).  Excel claims the data is corrupted.

```
curl 'https://qa.adsabs.harvard.edu/v1/author-affiliation/export' -H "authorization: Bearer:$ADS_DEV_KEY" -H 'content-type: application/json' -H 'accept: text/plain, */*; q=0.01' --data-binary '{"selected":["Accomazzi, Alberto|Harvard-Smithsonian Center for Astrophysics, Cambridge, USA|2017/10"],"format":["| Lastname, Firstname | Affiliation | Last Active Date | [excel]"]}' > aa.xls
```

**Comment by golnazads** [comment] 2018-02-25 21:00
Cool. I did not know you can sent the result of a curl to a file. thank you
so much.

Tried curl, just to be on the safe side, on the localhost and again got a
valid excel file.

It seems the issue is with the deployment. We are
using Microsoft.Office.Interop.Excel and it seems that is causing the
problem on the server. Shall be looking into a solution. thank you.

On Sun, Feb 25, 2018 at 3:00 PM, Alberto Accomazzi <notifications@github.com

**Comment by golnazads** [comment] 2018-02-27 00:16
As per Roman's suggestion looked into adsws as a cause of the problem, but was not able to see anything wrong stand out. Could follow the flow of control in adsws/api/discoverer/views.py from dispatcher to post calling the api and returning the result after checking for valid headers.

Noticed that the file created on the server for the same data is larger than the one created locally. Verified that the service creates the same size files both locally and on the server, it is afterward that some bytes get attached to the one on the server and corrupt it. Verified that the header content-length that is set correctly just before the service returns was also modified at some point and at the end contained the size of file transferred. 

I want to say the data gets jsonify somewhere before it is returned, but have no proof. Compared the two files byte for byte, most extra bytes are at the beginning of the corrupt file, where the header information for excel is saved.

So it seems the problem is not here.

**Comment by marblestation** [comment] 2018-02-27 18:43
This bug was finally linked to adsabs/adsws@1cc373f8d800202dce4c550e0d785cf1dadec34e and adsabs/bumblebee, a bugfix for the latter is being tested.

**Comment by marblestation** [comment] 2018-02-28 14:10
Followup issue: adsabs/bumblebee#1388

**Closed** 2018-03-12 12:02 UTC
